export const REMOVE_QUOTE_REQUEST__QUOTE = 'REMOVE_QUOTE_REQUEST__QUOTE';
export const REMOVE_QUOTE_SUCCESS__QUOTE = 'REMOVE_QUOTE_SUCCESS__QUOTE';
export const REMOVE_QUOTE_ERROR__QUOTE = 'REMOVE_QUOTE_ERROR__QUOTE';